spring:
  main:
    web-application-type: none
  data:
    cassandra:
      contact-points: 127.0.0.1
      port: 9042
      keyspace-name: dissertation
      local-datacenter: datacenter1
      schema-action: create-if-not-exists
      jmx-host: localhost
      jmx-port: 7199
      timeout: 15

generating:
  perCall: 150

compression:
  lz4:
    blockSize: 65536
  snappy:
    blockSize: 128
  zstd:
    compressionLevel: 1
    enableChecksum: false

application:
  type: benchmark # nonCompressed, onlyPreCompressed, preCompressed, cassandraCompressed, benchmark
  count: 100002
  benchmarkType: size # pageSize, read, fallback, size
  randomCount: false
  perTime: false # TBD

benchmark:
#  orders-count: 8000
  batch-sizes: [ 100 ]
  read-ratios: [ 0.5 ]
  chunk-sizes: [ 4096, 8192, 16384, 32768, 65536, 131072 ]
#  block-sizes: [ 4096, 8192]
#  bursts: 100
#  inter-burst-delay-ms: 1
  orders-count: 150000
  block-sizes: [ 524288, 1048576, 2097152, 4194304, 8388608, 16777216, 33554432, 67108864, 134217728]
#  chunk-sizes: [ 4, 8, 16, 32, 64, 128, 256 ]
#  batch-sizes: [ 50, 250, 500, 1000, 2000 ]
#  read-ratios: [ 0.25, 0.5, 0.75 ]
  bursts: 100
  inter-burst-delay-ms: 1
  parallel-bursts: 10
  warm-up-bursts: 10
  warm-up-delay-ms: 1