spring:
  main:
    web-application-type: none
  data:
    cassandra:
      contact-points: 127.0.0.1
      port: 9042
      keyspace-name: dissertation
      local-datacenter: datacenter1
      schema-action: create-if-not-exists
      jmx-host: localhost
      jmx-port: 7199
      timeout: 15

generating:
  perCall: 150

compression:
  lz4:
    blockSize: 65536
  snappy:
    blockSize: 128
  zstd:
    compressionLevel: 1
    enableChecksum: false

application:
  type: benchmark # nonCompressed, onlyPreCompressed, preCompressed, cassandraCompressed, benchmark
  count: 100002
  benchmarkType: fallback # pageSize, read, fallback, size
  randomCount: false
  perTime: false # TBD

benchmark:
  orders-count: 100000
  block-sizes: [ 4096 ]
  chunk-sizes: [ 1024, 2048]
  batch-sizes: [2000, 4000]
  parallel-bursts: 10
  inter-burst-delay-ms: 100

benchmark-orig:
  orders-count: 100000
  block-sizes: [ 4096, 8192, 16384, 32768, 65536, 131072, 262144, 524288, 1048576, 2097152]
  chunk-sizes: [ 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048]
  batch-sizes: [ 50, 100, 500, 1000, 2000, 4000]
  parallel-bursts: 10
  inter-burst-delay-ms: 100