spring:
  main:
    web-application-type: none
  data:
    cassandra:
      contact-points: 127.0.0.1
      port: 9042
      keyspace-name: dissertation
      local-datacenter: datacenter1
      schema-action: create-if-not-exists
      jmx-host: localhost
      jmx-port: 7199

generating:
  perCall: 150

compression:
  lz4:
    blockSize: 65536
  snappy:
    blockSize: 128
  zstd:
    compressionLevel: 1
    enableChecksum: false

application:
  type: benchmark # nonCompressed, onlyPreCompressed, preCompressed, cassandraCompressed, benchmark
  count: 60000
  benchmarkType: fallback # pageSize, read, fallback
  randomCount: false
  perTime: false # TBD